### ISSUE TITLE
Bug: Pull Cloud Actors for AWS Panic

### ISSUE THREAD

**Issue by GoodmanBen** [dragondrop-cloud/cloud-concierge#45]
## Current State
Stack trace of error:
```
goroutine 1 [running]:
[github.com/dragondrop-cloud/cloud-concierge/main/internal/implementations/identify_cloud_actors.(*AWSLogQuerier).ExtractDataFromResourceResult(0xc0000b4200](http://github.com/dragondrop-cloud/cloud-concierge/main/internal/implementations/identify_cloud_actors.(*AWSLogQuerier).ExtractDataFromResourceResult(0xc0000b4200), {0xc000887000, 0x167d, 0x1800}, {0xc000450b28, 0x14}, 0x0)
        /go/src/internal/implementations/identify_cloud_actors/aws_log_querier.go:232 +0x6bd
[github.com/dragondrop-cloud/cloud-concierge/main/internal/implementations/identify_cloud_actors.(*AWSLogQuerier).cloudTrailEventHistorySearch(0xc000380a40](http://github.com/dragondrop-cloud/cloud-concierge/main/internal/implementations/identify_cloud_actors.(*AWSLogQuerier).cloudTrailEventHistorySearch(0xc000380a40)?, {0xc000a8fa78?, 0x40da6a?}, {0xc000450b28, 0x14}, {0xc000450af8?, 0x2000?}, {0xc000935d93, 0x9}, 0x0)
        /go/src/internal/implementations/identify_cloud_actors/aws_log_querier.go:209 +0x2f7
[github.com/dragondrop-cloud/cloud-concierge/main/internal/implementations/identify_cloud_actors.(*AWSLogQuerier).QueryForAllResources(0xc0000b4200](http://github.com/dragondrop-cloud/cloud-concierge/main/internal/implementations/identify_cloud_actors.(*AWSLogQuerier).QueryForAllResources(0xc0000b4200), {0x1835268, 0xc0003a4ab0})
        /go/src/internal/implementations/identify_cloud_actors/aws_log_querier.go:130 +0x225
[github.com/dragondrop-cloud/cloud-concierge/main/internal/implementations/identify_cloud_actors.(*IdentifyCloudActors).Execute(0xc0005c0050](http://github.com/dragondrop-cloud/cloud-concierge/main/internal/implementations/identify_cloud_actors.(*IdentifyCloudActors).Execute(0xc0005c0050), {0x1835268, 0xc0003a4ab0})
        /go/src/internal/implementations/identify_cloud_actors/identify_cloud_actors.go:62 +0xeb
main.(*Job).Run(0xc0005bc280, {0x1835268, 0xc0003a4ab0})
        /go/src/job.go:168 +0x4f8
main.main()
        /go/src/main.go:38 +0x25b
```

@yantao0527 please add your configuration details for the execution that produced these errors so that we can do our best to replicate the problem.

## Desired State
Resolve bug.

## Do I want to work on this issue? 
- Yes

**Comment by yantao0527** [comment]
- envfile https://github.com/yantao0527/cloud-concierge-example/blob/main/demo.env
- managed resource https://github.com/yantao0527/cloud-concierge-example/blob/main/terraform/networking/main.tf
- I add a new tag "Environment=dev" on ["aws_internet_gateway" "gw"] through AWS console. Then the program failed.
